name: CI Flywheel

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # It is recommended to not modify any of the following configuration unless you know what you are doing.
    # To update your SFTP configuration, update the previous values under the `env` key.
    name: Deploy

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4

      # Deploys to FTP
      - name: SFTP Deploy
        id: upload
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          server: ${{ secrets.SFTP_HOST }}
          port: 22
          sftp_only: true
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          # The local folder to copy, defaults to root project folder
          local_path: ./*
          # This was generated using the output of
          remote_path: '/home/PeninsulaValdes_german/public_html/wp-content/themes/agencias-chubut-patagonia/'